### ISSUE TITLE
Greek Municipalities: DSD URI's do not match

### ISSUE THREAD

**Issue by larjohn** [openbudgets/datasets#14] opened 2016-02-25 00:07 UTC
The URI in the DSD file is not the same with the one in the dataset referring to it. 

For instance it is budget-athens vs athens-budget.

It does not match for Thessaloniki either.

**Comment by skarampatakis** [comment] 2016-02-25 07:29
URIs for DSDs corrected.

**Comment by jindrichmynarz** [comment] 2016-02-25 08:28
@skarampatakis, can we close this issue? BTW, you can close issues directly via commit messages (see [here](https://help.github.com/articles/closing-issues-via-commit-messages/)), so there is a clear association between an issue and the commit that fixed it.

**Comment by skarampatakis** [comment] 2016-02-25 08:35
@jindrichmynarz thank you for your advice. I left it open to give time to check if everything is in place. In my opinion, is the issue creator the one who should close the issue.

**Comment by jindrichmynarz** [comment] 2016-02-25 08:50
OK. When submitting issues I prefer the assignee to close them and thus indicate that the issue is fixed. If I discover the issue not to be fixed, I simply reopen the issue. However, this is merely my subjective preference and you may prefer a different workflow.

**Closed as completed** 2016-03-05 19:14 UTC
