### ISSUE TITLE
Aragon qb:structure wrong

### ISSUE THREAD

**Issue by larjohn** [openbudgets/datasets#22] opened 2016-04-05 01:05 UTC
http://data.openbudgets.eu/resource/dataset/aragon-2012-expenditure a qb:DataSet ;
    obeu-dimension:budgetaryUnit http://dbpedia.org/page/Aragon ;
    obeu-dimension:operationCharacter obeu-operation:Expenditure ;
    obeu-dimension:fiscalYear http://reference.data.gov.uk/id/year/2012 ;
    obeu-attribute:currency http://data.openbudgets.eu/codelist/currency/EUR ;
    qb:structure http://example.openbudgets.eu/ontology/dsd/aragon-budget 

Notice the example subdomain

**Comment by jindrichmynarz** [comment] 2016-04-05 06:27
This effectively a duplicate of #20 (see [this comment](https://github.com/openbudgets/datasets/issues/20#issuecomment-205272465)).

@fathoni to clarify if this was already fixed for all Aragon datasets.

**Comment by fathoni** [comment] 2016-04-11 10:49
Fixed with the recent push. Checked by using the validator mentioned previously, the result for 2006-2014 are valid, but for 2015 & 2016 there are duplicate issue problem.

**Closed as completed** 2016-04-11 10:50 UTC
Labels: bug, duplicate
